apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{ include "frontend.labels" . | nindent 4 }}
data:
{{- if .Values.config }}
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- else }}
  UI_THEME: "light"
  WELCOME_MESSAGE: "Welcome to the demo frontend"
{{- end }}
